# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JYHPageControlSample' do
  
  use_frameworks!
  pod 'JYHPageControl', :git => 'https://github.com/YoungheeJang/JYHPageControl.git', :branch => 'develop'

end
